# Generated by Django 4.2.30 on 2026-10-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('original_snapshot', models.JSONField(help_text='Effective values at submission: field_number_seen, status, dbh_raw/dbh_unit/dbh_cm, height_raw/height_unit/height_m, x_m, y_m, and the revision they came from.')),
                ('corrected', models.JSONField(help_text='Proposed values (subset of dbh_raw, dbh_unit, height_raw, height_unit, x_m, y_m).')),
                ('reason', models.CharField(max_length=300)),
                ('evidence', models.CharField(help_text='Field-check sheet / photo / instrument log reference.', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed — approved for application'), ('applied', 'Applied — revision appended'), ('rejected', 'Rejected at review (terminal)'), ('failed', 'Application failed — safe to retry')], default='pending', max_length=10)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('failure_detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inventory.treemeasurement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Per-measurement revision order, starting at 1.')),
                ('changed_fields', models.JSONField(default=list, help_text='Canonical/raw fields this revision actually changed.')),
                ('dbh_raw', models.FloatField(blank=True, null=True)),
                ('dbh_unit', models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in')], max_length=2, null=True)),
                ('dbh_cm', models.FloatField(blank=True, null=True)),
                ('height_raw', models.FloatField(blank=True, null=True)),
                ('height_unit', models.CharField(blank=True, choices=[('m', 'm')], max_length=2, null=True)),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('x_m', models.FloatField()),
                ('y_m', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='revision', to='inventory.measurementcorrection')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='inventory.treemeasurement')),
            ],
            options={
                'ordering': ['measurement', 'sequence'],
                'unique_together': {('measurement', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='measurementcorrection',
            index=models.Index(fields=['measurement', 'status'], name='inventory_m_measure_fb6569_idx'),
        ),
    ]
