# Generated by Django 4.2.30 on 2026-10-04 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(help_text='Client-generated key; repeats return the same correction.', max_length=80, unique=True)),
                ('reason', models.CharField(max_length=400)),
                ('evidence', models.JSONField(help_text='Evidence list, e.g. [{type: photo, ref: ..., note: ...}].')),
                ('original_dbh_raw', models.FloatField(blank=True, null=True)),
                ('original_dbh_unit', models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in')], max_length=2, null=True)),
                ('original_dbh_cm', models.FloatField(blank=True, null=True)),
                ('original_height_raw', models.FloatField(blank=True, null=True)),
                ('original_height_unit', models.CharField(blank=True, choices=[('m', 'm')], max_length=2, null=True)),
                ('original_height_m', models.FloatField(blank=True, null=True)),
                ('original_x_m', models.FloatField()),
                ('original_y_m', models.FloatField()),
                ('original_status', models.CharField(choices=[('alive_measured', 'Alive and remeasured'), ('alive_not_measured', 'Alive but not measured (missing data)'), ('dead', 'Dead (mortality observation)'), ('missing_tree', 'Tree not located')], max_length=20)),
                ('corrected_dbh_raw', models.FloatField(blank=True, null=True)),
                ('corrected_dbh_unit', models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in')], max_length=2, null=True)),
                ('corrected_dbh_cm', models.FloatField(blank=True, null=True)),
                ('corrected_height_raw', models.FloatField(blank=True, null=True)),
                ('corrected_height_unit', models.CharField(blank=True, choices=[('m', 'm')], max_length=2, null=True)),
                ('corrected_height_m', models.FloatField(blank=True, null=True)),
                ('corrected_x_m', models.FloatField()),
                ('corrected_y_m', models.FloatField()),
                ('corrected_status', models.CharField(choices=[('alive_measured', 'Alive and remeasured'), ('alive_not_measured', 'Alive but not measured (missing data)'), ('dead', 'Dead (mortality observation)'), ('missing_tree', 'Tree not located')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed — approved, awaiting application'), ('applied', 'Applied — effective revision issued'), ('rejected', 'Rejected by reviewer'), ('failed', 'Application incomplete/failed — retry or reject')], default='pending', max_length=10)),
                ('submitted_by', models.CharField(blank=True, max_length=80)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=80)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=400)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbh_cm', models.FloatField(blank=True, null=True)),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('x_m', models.FloatField()),
                ('y_m', models.FloatField()),
                ('status', models.CharField(choices=[('alive_measured', 'Alive and remeasured'), ('alive_not_measured', 'Alive but not measured (missing data)'), ('dead', 'Dead (mortality observation)'), ('missing_tree', 'Tree not located')], max_length=20)),
                ('dbh_raw', models.FloatField(blank=True, null=True)),
                ('dbh_unit', models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in')], max_length=2, null=True)),
                ('height_raw', models.FloatField(blank=True, null=True)),
                ('height_unit', models.CharField(blank=True, choices=[('m', 'm')], max_length=2, null=True)),
                ('revision_status', models.CharField(choices=[('pending', 'Pending — application interrupted, not authoritative'), ('effective', 'Effective — authoritative corrected values'), ('superseded', 'Superseded by a later correction (audit chain)'), ('void', 'Void — abandoned incomplete attempt')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=400)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revision_attempts', to='inventory.measurementcorrection')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='inventory.treemeasurement')),
                ('supersedes', models.ForeignKey(blank=True, help_text='The effective revision this one replaces, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='inventory.measurementrevision')),
            ],
            options={
                'ordering': ['measurement_id', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='measurementcorrection',
            name='based_on_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_corrections', to='inventory.measurementrevision'),
        ),
        migrations.AddField(
            model_name='measurementcorrection',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inventory.treemeasurement'),
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='measurement_revisions',
            field=models.ManyToManyField(blank=True, related_name='estimate_versions', to='inventory.measurementrevision'),
        ),
        migrations.AddField(
            model_name='identityconflict',
            name='triggered_by_correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_conflicts', to='inventory.measurementcorrection'),
        ),
        migrations.AddIndex(
            model_name='measurementrevision',
            index=models.Index(fields=['measurement', 'revision_status'], name='inventory_m_measure_684ca5_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurementrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('revision_status', 'effective')), fields=('measurement',), name='uniq_effective_revision_per_measurement'),
        ),
    ]
